apiVersion: v1
kind: Pod 
spec:
  serviceAccountName: jenkins
  containers:
  - name: kubectl
    command:
    - cat 
    tty: true
    image: lachlanevenson/k8s-kubectl:v1.8.8
  - name: helm
    command:
    - cat 
    tty: true
    image: lachlanevenson/k8s-helm:latest

