FROM jenkins/jenkins:lts
USER root

#Pre-Install Jenkins Plugins
COPY plugins-master.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

USER jenkins
